name: PR Checks
on:
  pull_request:
    branches: [main, mock-main]

permissions:
  contents: write
  pull-requests: write
    
jobs:
  test1:
    name: Test 1
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 5
          echo "Test1 passed"
  test2:
    name: Test 2
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 5
          echo "Test 2 passed"

  all-checks-passed: 
    name: All Checks Passed 
    if: always()
    needs:
      - test1
      - test2
    runs-on: ubuntu-latest
    steps:
      - name: Ensure all required jobs pass successfully
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}

  auto-merge:
    name: Auto-Merge Admin PR After All Checks Passed
    if: success() && ${{ contains(fromJson('["andywpt"]'), github.actor) }}
    needs: all-checks-passed
    runs-on: ubuntu-latest
    steps:
      - name: Create github app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.ADMIN_BOT_APP_ID }}
          private-key: ${{ secrets.ADMIN_BOT_KEY }}

      - name: Approve and squash the pull request
        env: 
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_URL: ${{github.event.pull_request.html_url}}
        run: |
          gh auth status
          gh pr review --approve "$PR_URL"
          gh pr merge --admin -s "$PR_URL"