name: Run unit tests

on:
  workflow_dispatch:
  push:

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Load passphrase from secrets
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          echo "${PASSPHRASE}" > passphrase

      - name: Generate project
        run: |
          make
      
      - name: Run unit tests
        run: |
          xcodebuild test \
          -workspace AibaShop.xcworkspace \
          -scheme Production \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0' \
          | xcpretty