name: Run tests

on:
  workflow_dispatch:
  push:

jobs:
  run-tests:
    name: Run tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Load cached Pod derived data
        uses: actions/cache@v4
        with:
          path: .local_derived_data
          key: test-pods-derived-data-${{ hashFiles('**/Podfile.lock') }}

      - name: Cache/Restore Mint packages
        id: mint-cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/mint
          key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}

      - name: Install command line tool (if not yet cached)
        if: steps.mint-cache.outputs.cache-hit != 'true'
        run: mint bootstrap

      - name: Generate project
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          echo "${PASSPHRASE}" > passphrase
          make

      - name: Run unit tests
        run: |
          gem uninstall fastlane --silent
          sudo xcode-select --switch /Applications/Xcode_16.0.app
          set -a && \
          source fastlane/.fastlane.env && \
          source Configurations/Decrypted/.fastlane.private.env && \
          set +a && \
          fastlane ios run_unit_tests
          