name: Run tests

on:
  workflow_dispatch:
  push:

jobs:
  run-tests:
    name: Run tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load passphrase from secrets
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          echo "${PASSPHRASE}" > passphrase

      - name: Generate project
        run: |
          make

      - name: Load cached Pod derived data
        uses: actions/cache@v4
        with:
          path: .local_derived_data
          key: test-pods-derived-data-${{ hashFiles('**/Podfile.lock') }}
      
      - name: Run unit tests
        run: |
          gem uninstall fastlane --silent
          sudo xcode-select --switch /Applications/Xcode_16.0.app
          xcrun simctl list devices
          set -a && \
          source fastlane/.fastlane.env && \
          source Configurations/Decrypted/.fastlane.private.env && \
          set +a && \
          fastlane ios run_unit_tests
          chmod +x Configurations/Make/unit_test.sh
          Configurations/Make/unit_test.sh