name: Update Cache On Main Branch

on:
  push: 
    branches: main

jobs:
  run-tests:
    name: Run tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
          bundler-cache: true

      - name: Cache/Restore Pod derived data
        id: pod-cache
        uses: actions/cache@v4
        with:
          path: .local_derived_data
          key: test-pods-derived-data-${{ hashFiles('**/Podfile.lock') }}
          lookup-only: true

      - name: Generate project
        if: steps.pod-cache.outputs.cache-hit != 'true'
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
        run: |
          echo "${PASSPHRASE}" > passphrase
          make
  
      - name: Run unit tests
        if: steps.pod-cache.outputs.cache-hit != 'true'
        run: |
          sudo xcode-select --switch /Applications/Xcode_16.0.app
          set -a && \
          source fastlane/.fastlane.env && \
          source Configurations/Decrypted/.fastlane.private.env && \
          set +a && \
          bundle exec fastlane ios run_unit_tests